### ISSUE TITLE
Fail to get flask app context instance inside a celery task

### ISSUE THREAD

**Issue by fengyc** [inveniosoftware/flask-celeryext#10]
Hi,

I am trying to integrate flask-mail with celery. Flask-mail need a flask application context, I wrote the test code like this:

    from flask import Flask
    from flask.ext.celeryext import FlaskCeleryExt

    app = Flask('example')
    app.config['BROKER_URL'] = 'amqp://guest:guest@127.0.0.1:5672//'
    app.config['CELERY_RESULT_BACKEND'] = None

    ext = FlaskCeleryExt(app)
    celery = ext.celery

    @celery.task(name='test')
    def test():
        from flask import current_app
        assert current_app._get_current_object() is not None

    if __name__ == '__main__':
        result = test.delay()

Then, run the celery worker:

    celery worker -A test.celery --loglevel=info

And test the script:

    python test.py

But it doesn't work. I got an exception: `RuntimeError: working outside of application context`

I google it and fixed it like this:

    if __name__ == '__main__':
        result = test.delay()
    else:
        print('*** push app context ***')
        app.app_context().push()

It works. 

Do I have to push a flask application context manually or misunderstand something ?

Thanks.

**Comment by lnielsen** [comment]
Thanks for reporting the issue. I've tried your code above, and for me it works fine without your extra fix. 
Only change I did was to use Redis as broker: ``app.config['BROKER_URL'] = 'redis://localhost:6379/1'``

```console
$ mkvirtualenv test
(test)$ pip install flask-celeryext redis
...
Successfully installed Flask-0.10.1 Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.4 amqp-1.4.9 anyjson-0.3.3 billiard-3.3.0.22 celery-3.1.20 flask-celeryext-0.2.0 itsdangerous-0.24 kombu-3.0.33 pytz-2015.7 redis-2.10.5
(test) $ python test.py
(test) $ celery worker -A test.celery -l INFO
...
[...] Received task: test[97fcf8ba-883d-4f1f-8f96-10a6af1d2038]
[...: INFO/MainProcess] Task test[97fcf8ba-883d-4f1f-8f96-10a6af1d2038] succeeded in 0.0008214759873226285s: None
```

**Comment by fengyc** [comment]
Thanks @lnielsen . You are right. I've tried the code again and found it works fine on linux / cygwin. It goes wrong just on windows. So, might be a compatibility problem.
