### ISSUE TITLE
Multiple versions of Documentation?

### ISSUE THREAD

**Issue by fuhrysteve** [inveniosoftware/flask-celeryext#11]
The README points you here:
http://flask-celeryext.readthedocs.org/en/latest/

But elsewhere, I came across this:
http://pythonhosted.org/Flask-CeleryExt/

Can you please clarify or update the README? Thanks!

**Comment by tiborsimko** [comment]
Yes, we should streamline the doc publishing process indeed.  The main difference is currently:

- pythonhosted has docs built from the latest released version on PyPI;
- readthedocs has docs built from the latest `master` branch commit (plus has docs for past versions).

**Comment by fuhrysteve** [comment]
Hmm, I think the issue might actually be that the docs for readthedocs is messed up. It almost seems to be truncated or something.
