### ISSUE TITLE
global: message signing

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/flask-celeryext#17]
### Proposal

Improve security of default configuration.

Shall we consider moving implementation from https://github.com/inveniosoftware/invenio/pull/3201 here?

cc @inveniosoftware/triagers

**Comment by lnielsen** [comment]
Is it worthwhile the effort? Perhaps time is better spend on ensuring we use SSL everywhere (redis, db, rabbitmq, …)?

**Comment by jirikuncar** [comment]
Sure. I just wanted to make an record since inveniosoftware/invenio#3201 has been closed recently without follow-up.
