### ISSUE TITLE
does this support celery 4? and what is the difference between you guys and other flask-celery extensions?

### ISSUE THREAD

**Issue by rlam3** [inveniosoftware/flask-celeryext#27]
does this support celery 4?

what is the difference between:
https://github.com/Robpol86/Flask-Celery-Helper/i
https://github.com/ask/flask-celery
https://github.com/inveniosoftware/flask-celeryext

**Comment by lnielsen** [comment]
We support celery 4 since the latest v0.3.0 release last week.
