### ISSUE TITLE
Circular imports problem?

### ISSUE THREAD

**Issue by rlam3** [inveniosoftware/flask-celeryext#3]
Does this add on take into account circular imports that celery has when using the application factory method of creating the celery app? How is this fixed? Do you do local imports inside the function instead?

**Comment by jirikuncar** [comment]
@rlam3 can you provide an example of your problem?

**Comment by lnielsen** [comment]
You can solve this by using the ``@shared_task`` decorator + the connect to the ``import_modules`` celery signal. See https://github.com/inveniosoftware/invenio-celery/blob/master/invenio_celery/ext.py#L86-L91
