### ISSUE TITLE
A imports circle

### ISSUE THREAD

**Issue by bydeath** [inveniosoftware/flask-celeryext#32]
I am faced with the same problem like [issures3](https://github.com/inveniosoftware/flask-celeryext/issues/3)
A import circle: celery->app->bluepint->views->celery task->celery
celery initializing need to import app, I using bluepoint to register modules, bluepoint need to import views, views call celery tasks, in tasks.py there is celery import.

**Comment by lnielsen** [comment]
Please see [example](https://github.com/inveniosoftware/flask-celeryext/issues/3#issuecomment-386221056) of how to solve this.
