### ISSUE TITLE
Make a v0.3.3 release?

### ISSUE THREAD

**Issue by pmdarrow** [inveniosoftware/flask-celeryext#39]
Wondering if you could cut a 0.3.3 release that includes https://github.com/inveniosoftware/flask-celeryext/commit/cf8513d249896e1770ff098e00df0e90250124b1?

**Comment by pmdarrow** [comment]
@slint @Glignos @lnielsen any thoughts about this?

**Comment by lnielsen** [comment]
Closed by c9dac531514e2b9208409166ca6e6d7dca3d314a. Sorry for the delay.
