### ISSUE TITLE
app.config['CELERY_BROKER_URL'] doesn't get passsed in create_celery_app

### ISSUE THREAD

**Issue by flexlee** [inveniosoftware/flask-celeryext#4]
In http://flask.pocoo.org/docs/0.10/patterns/celery/ , there is specific argument that broker=app.config['CELERY_BROKER_URL']  to make_celery(app)

**Comment by jirikuncar** [comment]
@flexlee thank you for reporting. Can you check if https://github.com/inveniosoftware/flask-celeryext/pull/5 solves your issue?

**Comment by jirikuncar** [comment]
@flexlee looking deeply into `celery` code it should be possible to use `BROKER_URL` (http://docs.celeryproject.org/en/latest/_modules/celery/app/base.html#Celery.connection) without modification of `flask-celeryext`.
